/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/openshift/api/operator/v1"
)

// TrustedCABundleSpecApplyConfiguration represents an declarative configuration of the TrustedCABundleSpec type for use
// with apply.
type TrustedCABundleSpecApplyConfiguration struct {
	ManagementState *v1.ManagementState `json:"managementState,omitempty"`
	CustomCABundle  *string             `json:"customCABundle,omitempty"`
}

// TrustedCABundleSpecApplyConfiguration constructs an declarative configuration of the TrustedCABundleSpec type for use with
// apply.
func TrustedCABundleSpec() *TrustedCABundleSpecApplyConfiguration {
	return &TrustedCABundleSpecApplyConfiguration{}
}

// WithManagementState sets the ManagementState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementState field is set to the value of the last call.
func (b *TrustedCABundleSpecApplyConfiguration) WithManagementState(value v1.ManagementState) *TrustedCABundleSpecApplyConfiguration {
	b.ManagementState = &value
	return b
}

// WithCustomCABundle sets the CustomCABundle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomCABundle field is set to the value of the last call.
func (b *TrustedCABundleSpecApplyConfiguration) WithCustomCABundle(value string) *TrustedCABundleSpecApplyConfiguration {
	b.CustomCABundle = &value
	return b
}
