/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/opendatahub-io/opendatahub-operator/v2/apis/dscinitialization/v1"
	dscinitializationv1 "github.com/opendatahub-io/opendatahub-operator/v2/pkg/client/applyconfiguration/dscinitialization/v1"
	scheme "github.com/opendatahub-io/opendatahub-operator/v2/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DSCInitializationsGetter has a method to return a DSCInitializationInterface.
// A group's client should implement this interface.
type DSCInitializationsGetter interface {
	DSCInitializations() DSCInitializationInterface
}

// DSCInitializationInterface has methods to work with DSCInitialization resources.
type DSCInitializationInterface interface {
	Create(ctx context.Context, dSCInitialization *v1.DSCInitialization, opts metav1.CreateOptions) (*v1.DSCInitialization, error)
	Update(ctx context.Context, dSCInitialization *v1.DSCInitialization, opts metav1.UpdateOptions) (*v1.DSCInitialization, error)
	UpdateStatus(ctx context.Context, dSCInitialization *v1.DSCInitialization, opts metav1.UpdateOptions) (*v1.DSCInitialization, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.DSCInitialization, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DSCInitializationList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DSCInitialization, err error)
	Apply(ctx context.Context, dSCInitialization *dscinitializationv1.DSCInitializationApplyConfiguration, opts metav1.ApplyOptions) (result *v1.DSCInitialization, err error)
	ApplyStatus(ctx context.Context, dSCInitialization *dscinitializationv1.DSCInitializationApplyConfiguration, opts metav1.ApplyOptions) (result *v1.DSCInitialization, err error)
	DSCInitializationExpansion
}

// dSCInitializations implements DSCInitializationInterface
type dSCInitializations struct {
	client rest.Interface
}

// newDSCInitializations returns a DSCInitializations
func newDSCInitializations(c *DscinitializationV1Client) *dSCInitializations {
	return &dSCInitializations{
		client: c.RESTClient(),
	}
}

// Get takes name of the dSCInitialization, and returns the corresponding dSCInitialization object, and an error if there is any.
func (c *dSCInitializations) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DSCInitialization, err error) {
	result = &v1.DSCInitialization{}
	err = c.client.Get().
		Resource("dscinitializations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DSCInitializations that match those selectors.
func (c *dSCInitializations) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DSCInitializationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DSCInitializationList{}
	err = c.client.Get().
		Resource("dscinitializations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dSCInitializations.
func (c *dSCInitializations) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("dscinitializations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dSCInitialization and creates it.  Returns the server's representation of the dSCInitialization, and an error, if there is any.
func (c *dSCInitializations) Create(ctx context.Context, dSCInitialization *v1.DSCInitialization, opts metav1.CreateOptions) (result *v1.DSCInitialization, err error) {
	result = &v1.DSCInitialization{}
	err = c.client.Post().
		Resource("dscinitializations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dSCInitialization).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dSCInitialization and updates it. Returns the server's representation of the dSCInitialization, and an error, if there is any.
func (c *dSCInitializations) Update(ctx context.Context, dSCInitialization *v1.DSCInitialization, opts metav1.UpdateOptions) (result *v1.DSCInitialization, err error) {
	result = &v1.DSCInitialization{}
	err = c.client.Put().
		Resource("dscinitializations").
		Name(dSCInitialization.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dSCInitialization).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *dSCInitializations) UpdateStatus(ctx context.Context, dSCInitialization *v1.DSCInitialization, opts metav1.UpdateOptions) (result *v1.DSCInitialization, err error) {
	result = &v1.DSCInitialization{}
	err = c.client.Put().
		Resource("dscinitializations").
		Name(dSCInitialization.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dSCInitialization).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dSCInitialization and deletes it. Returns an error if one occurs.
func (c *dSCInitializations) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("dscinitializations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dSCInitializations) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("dscinitializations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dSCInitialization.
func (c *dSCInitializations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DSCInitialization, err error) {
	result = &v1.DSCInitialization{}
	err = c.client.Patch(pt).
		Resource("dscinitializations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied dSCInitialization.
func (c *dSCInitializations) Apply(ctx context.Context, dSCInitialization *dscinitializationv1.DSCInitializationApplyConfiguration, opts metav1.ApplyOptions) (result *v1.DSCInitialization, err error) {
	if dSCInitialization == nil {
		return nil, fmt.Errorf("dSCInitialization provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(dSCInitialization)
	if err != nil {
		return nil, err
	}
	name := dSCInitialization.Name
	if name == nil {
		return nil, fmt.Errorf("dSCInitialization.Name must be provided to Apply")
	}
	result = &v1.DSCInitialization{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("dscinitializations").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *dSCInitializations) ApplyStatus(ctx context.Context, dSCInitialization *dscinitializationv1.DSCInitializationApplyConfiguration, opts metav1.ApplyOptions) (result *v1.DSCInitialization, err error) {
	if dSCInitialization == nil {
		return nil, fmt.Errorf("dSCInitialization provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(dSCInitialization)
	if err != nil {
		return nil, err
	}

	name := dSCInitialization.Name
	if name == nil {
		return nil, fmt.Errorf("dSCInitialization.Name must be provided to Apply")
	}

	result = &v1.DSCInitialization{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("dscinitializations").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
