/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/opendatahub-io/opendatahub-operator/v2/apis/features/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FeatureTrackerLister helps list FeatureTrackers.
// All objects returned here must be treated as read-only.
type FeatureTrackerLister interface {
	// List lists all FeatureTrackers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.FeatureTracker, err error)
	// Get retrieves the FeatureTracker from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.FeatureTracker, error)
	FeatureTrackerListerExpansion
}

// featureTrackerLister implements the FeatureTrackerLister interface.
type featureTrackerLister struct {
	indexer cache.Indexer
}

// NewFeatureTrackerLister returns a new FeatureTrackerLister.
func NewFeatureTrackerLister(indexer cache.Indexer) FeatureTrackerLister {
	return &featureTrackerLister{indexer: indexer}
}

// List lists all FeatureTrackers in the indexer.
func (s *featureTrackerLister) List(selector labels.Selector) (ret []*v1.FeatureTracker, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.FeatureTracker))
	})
	return ret, err
}

// Get retrieves the FeatureTracker from the index for a given name.
func (s *featureTrackerLister) Get(name string) (*v1.FeatureTracker, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("featuretracker"), name)
	}
	return obj.(*v1.FeatureTracker), nil
}
