/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	featuresv1 "github.com/opendatahub-io/opendatahub-operator/v2/apis/features/v1"
	versioned "github.com/opendatahub-io/opendatahub-operator/v2/pkg/client/clientset/versioned"
	internalinterfaces "github.com/opendatahub-io/opendatahub-operator/v2/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/opendatahub-io/opendatahub-operator/v2/pkg/client/listers/features/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// FeatureTrackerInformer provides access to a shared informer and lister for
// FeatureTrackers.
type FeatureTrackerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.FeatureTrackerLister
}

type featureTrackerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewFeatureTrackerInformer constructs a new informer for FeatureTracker type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFeatureTrackerInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredFeatureTrackerInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredFeatureTrackerInformer constructs a new informer for FeatureTracker type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFeatureTrackerInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FeaturesV1().FeatureTrackers().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FeaturesV1().FeatureTrackers().Watch(context.TODO(), options)
			},
		},
		&featuresv1.FeatureTracker{},
		resyncPeriod,
		indexers,
	)
}

func (f *featureTrackerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredFeatureTrackerInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *featureTrackerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&featuresv1.FeatureTracker{}, f.defaultInformer)
}

func (f *featureTrackerInformer) Lister() v1.FeatureTrackerLister {
	return v1.NewFeatureTrackerLister(f.Informer().GetIndexer())
}
