/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/opendatahub-io/opendatahub-operator/v2/apis/datasciencecluster/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// DataScienceClusterLister helps list DataScienceClusters.
// All objects returned here must be treated as read-only.
type DataScienceClusterLister interface {
	// List lists all DataScienceClusters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.DataScienceCluster, err error)
	// Get retrieves the DataScienceCluster from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.DataScienceCluster, error)
	DataScienceClusterListerExpansion
}

// dataScienceClusterLister implements the DataScienceClusterLister interface.
type dataScienceClusterLister struct {
	indexer cache.Indexer
}

// NewDataScienceClusterLister returns a new DataScienceClusterLister.
func NewDataScienceClusterLister(indexer cache.Indexer) DataScienceClusterLister {
	return &dataScienceClusterLister{indexer: indexer}
}

// List lists all DataScienceClusters in the indexer.
func (s *dataScienceClusterLister) List(selector labels.Selector) (ret []*v1.DataScienceCluster, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.DataScienceCluster))
	})
	return ret, err
}

// Get retrieves the DataScienceCluster from the index for a given name.
func (s *dataScienceClusterLister) Get(name string) (*v1.DataScienceCluster, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("datasciencecluster"), name)
	}
	return obj.(*v1.DataScienceCluster), nil
}
