/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	datascienceclusterv1 "github.com/opendatahub-io/opendatahub-operator/v2/apis/datasciencecluster/v1"
	versioned "github.com/opendatahub-io/opendatahub-operator/v2/pkg/client/clientset/versioned"
	internalinterfaces "github.com/opendatahub-io/opendatahub-operator/v2/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/opendatahub-io/opendatahub-operator/v2/pkg/client/listers/datasciencecluster/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DataScienceClusterInformer provides access to a shared informer and lister for
// DataScienceClusters.
type DataScienceClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DataScienceClusterLister
}

type dataScienceClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewDataScienceClusterInformer constructs a new informer for DataScienceCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDataScienceClusterInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDataScienceClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredDataScienceClusterInformer constructs a new informer for DataScienceCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDataScienceClusterInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DatascienceclusterV1().DataScienceClusters().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DatascienceclusterV1().DataScienceClusters().Watch(context.TODO(), options)
			},
		},
		&datascienceclusterv1.DataScienceCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *dataScienceClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDataScienceClusterInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dataScienceClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&datascienceclusterv1.DataScienceCluster{}, f.defaultInformer)
}

func (f *dataScienceClusterInformer) Lister() v1.DataScienceClusterLister {
	return v1.NewDataScienceClusterLister(f.Informer().GetIndexer())
}
